#! /usr/bin/env bash

directories="$HOME/code $HOME/.config $HOME/worktrees"

tmux-sessionizer $(find $directories -mindepth 1 -maxdepth 1 -type d 2>/dev/null \
    | fzf --preview 'eza --color=always --icons --oneline --all {}' --height=40% --reverse --style=full --bind 'enter:become(tmux-sessionizer {})')

