#! /usr/bin/env fish

set PROFILE_FILE ~/.local/share/profile/current

function usage
    echo "Usage: profile <status|switch> [args]"
    echo ""
    echo "Commands:"
    echo "  status"
    echo "  switch <profile-name>"
end

function set_personal_profile
    echo $profile_name > $PROFILE_FILE

    handlr set x-scheme-handler/https librewolf.desktop

    profile_status
    exit 0
end

function set_work_profile
    echo $profile_name > $PROFILE_FILE

    handlr set x-scheme-handler/https google-chrome.desktop

    profile_status
    exit 0
end

function profile_status
    if test -e "$PROFILE_FILE"
        cat $PROFILE_FILE
        handlr list
    else
        echo $PROFILE_FILE
        echo "profile file not found"
    end
end

function profile_switch
    set -l profile_name $argv[1]

    if test -z "$profile_name"
        echo "Usage: profile switch <profile-name>"
        exit 1
    end
    
    if not test -e "$PROFILE_FILE"
        mkdir -p (dirname $PROFILE_FILE)
        touch $PROFILE_FILE
    end

    switch $profile_name
        case "personal"
            set_personal_profile
        case "work"
            set_work_profile
        case "*"
            echo "profile $profile_name not recognized"
            exit 1
    end
end

set -l command $argv[1]

if test -z "$command"
    usage
    exit 1
end

set -e argv[1]

switch $command
    case status
        profile_status $argv
    case switch
        profile_switch $argv
    case help -h --help
        usage
    case '*'
        echo "Unknown subcommand: $command"
        usage
        exit 1
end
