#! /usr/bin/env fish

set PROFILE_FILE ~/.local/share/profile/current
set OPENCODE_AUTH_PATH ~/.local/share/opencode/auth.json
set OPENCODE_AUTH_PROFILES_DIR ~/.local/share/opencode/profiles

function usage
    echo "Usage: profile <status|switch> [args]"
    echo ""
    echo "Commands:"
    echo "  status"
    echo "  switch <profile-name>"
end

# ensures everything is setup properly
function preflight
    if not test  -d "$OPENCODE_AUTH_PROFILES_DIR"
        mkdir -p $OPENCODE_AUTH_PROFILES_DIR
    end

    if test -e "$OPENCODE_AUTH_PATH" && not test -L "$OPENCODE_AUTH_PATH"
        echo "opencode auth.json is not a symlink. Move your current auth.json into the correct subdir before running this command"
        exit 1
    end
end

function set_personal_profile
    echo $profile_name > $PROFILE_FILE

    handlr set x-scheme-handler/https librewolf.desktop
    ln --symbolic --force $OPENCODE_AUTH_PROFILES_DIR/personal.json $OPENCODE_AUTH_PATH

    profile_status
    exit 0
end

function set_work_profile
    echo $profile_name > $PROFILE_FILE

    handlr set x-scheme-handler/https google-chrome.desktop
    ln --symbolic --force $OPENCODE_AUTH_PROFILES_DIR/work.json $OPENCODE_AUTH_PATH

    profile_status
    exit 0
end

function profile_status
    if test -e "$PROFILE_FILE"
        cat $PROFILE_FILE
        handlr list
        ls -al $OPENCODE_AUTH_PATH
    else
        echo $PROFILE_FILE
        echo "profile file not found"
    end
end

function profile_switch
    set -l profile_name $argv[1]

    if test -z "$profile_name"
        echo "Usage: profile switch <profile-name>"
        exit 1
    end
    
    if not test -e "$PROFILE_FILE"
        mkdir -p (dirname $PROFILE_FILE)
        touch $PROFILE_FILE
    end

    switch $profile_name
        case "personal"
            set_personal_profile
        case "work"
            set_work_profile
        case "*"
            echo "profile $profile_name not recognized"
            exit 1
    end
end

preflight

set -l command $argv[1]

if test -z "$command"
    usage
    exit 1
end

set -e argv[1]

switch $command
    case status
        profile_status $argv
    case switch
        profile_switch $argv
    case active
        cat $PROFILE_FILE
    case help -h --help
        usage
    case '*'
        echo "Unknown subcommand: $command"
        usage
        exit 1
end
