#!/usr/bin/env bash

directory=$1
printf '%s\n' "$directory"

if [[ -z $directory ]]; then
    exit 0
fi

cd "$directory" || exit 1
directory=$PWD

if command -v zoxide >/dev/null 2>&1; then
    zoxide add -- "$directory"
fi

session_name=$(basename "$directory")

tmux new-session -ds "$session_name"

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi
