monitorv2 {
  output = DP-1
  mode = 3840x2160@144
  position = 0x0
  scale = 1
  bitdepth = 10
  cm = hdr
  sdrbrightness = 1.10
  sdrsaturation = 1.0
  sdr_max_luminance = 220
  sdr_min_luminance = 0.005
  sdr_eotf = 1
}

monitorv2 {
  output = HDMI-A-1
  mode = 3440x1440@60
  position = -3440x0
  scale = 1
  bitdepth = 10
  cm = hdr
  sdrbrightness = 0.8
  sdrsaturation = 0.98
  sdr_max_luminance = 220
  sdr_min_luminance = 0.005
  sdr_eotf = 1
}
