"$schema" = 'https://starship.rs/config-schema.json'

format = """
[$hostname$os$username](bg:blue fg:mantle)\
[$directory](bg:yellow fg:mantle)\
[$git_branch$git_status](bg:peach fg:mantle)\
[$python](bg:green fg:mantle)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
mauve = "#cba6f7"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[hostname]
ssh_only = true
ssh_symbol = '󰑔 '
format = ' $ssh_symbol$hostname'

[os]
disabled = false
format = ' $symbol'

[os.symbols]
Windows = "󰍲"
Linux = "󰌽"
Arch = "󰣇"
Debian = "󰣚"
NixOS = ""

[username]
show_always = true
format = ' $user '

[directory]
format = " $path "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "
"dotfiles" = " "

[git_branch]
symbol = ""
format = ' $symbol $branch '

[git_status]
format = '$all_status$ahead_behind '

[python]
symbol = ""
format = ' $symbol $version $virtualenv '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
