#! /bin/zsh

set -eux

# Detect session type
if [ "$XDG_SESSION_TYPE" = "x11" ] || [ "$XDG_SESSION_TYPE" = "xorg" ]; then
    # Xorg session - use existing code
    chosen=$(autorandr --list | rofi -dmenu -i)
    
    autorandr --load $chosen --skip-options crtc
    # if pollybar is running, restart it
    if  pgrep -x "polybar"; then
        echo "restarting polybar"
        sleep 2
        ~/.config/polybar/launch_polybar.sh
    fi
    nitrogen --restore
else
    # Wayland session
    # Add your Wayland-specific screen layout code here
    env
    hyprmon list
    chosen=$(hyprmon list | rofi -dmenu -i)
    hyprmon load $chosen
fi
