#! /bin/sh

chosen=$(command ls ~/.screenlayout | rofi -dmenu -i)

~/.screenlayout/$chosen
# if pollybar is running, restart it
if  pgrep -x "polybar"; then
    echo "restarting polybar"
    sleep 2
    ~/.config/polybar/launch_polybar.sh
fi
nitrogen --restore
