#! /bin/sh

chosen=$(autorandr --list | rofi -dmenu -i)

autorandr --load $chosen --skip-options crtc
# if pollybar is running, restart it
if  pgrep -x "polybar"; then
    echo "restarting polybar"
    sleep 2
    ~/.config/polybar/launch_polybar.sh
fi
nitrogen --restore
