#! /bin/bash
echo "checking for updates..."
if ! updates=$(checkupdates 2> /dev/null | wc -l ); then
    updates=0
fi

if [ "$updates" -gt 0 ]; then
    notify-send "Update" "$updates packages out of date"
    curl -d "System $(cat /etc/hostname) has $updates updates available" https://ntfy.rileymathews.com/home-server-alerts
else
    echo "no updates"
fi
