#! /bin/sh

xset -dpms
xset s off
xrdb -merge "$HOME/.config/X11/.Xresources"
xsetroot -solid "#000000"
xidlehook \
    --not-when-audio \
    --not-when-fullscreen \
    --timer 300 \
    'betterlockscreen -l' \
    '' &
