Section "ServerLayout"
    Identifier "NVIDIA primary layout"
    Screen 0 "NVIDIA screen"
    Inactive "Intel GPU"
EndSection

Section "Device"
    Identifier "NVIDIA GPU"
    Driver "nvidia"
    BusID "PCI:2:0:0"
    Option "AllowEmptyInitialConfiguration" "true"
    Option "PrimaryGPU" "yes"
EndSection

Section "Screen"
    Identifier "NVIDIA screen"
    Device "NVIDIA GPU"
EndSection

Section "Device"
    Identifier "Intel GPU"
    Driver "modesetting"
    BusID "PCI:0:2:0"
EndSection

Section "Screen"
    Identifier "Intel screen"
    Device "Intel GPU"
EndSection
