# Format string defining the prompt
format = "$username@$hostname:$directory$character"

# Disable all modules except those required
[username]
disabled = false
show_always = true
format = "[$user](green)"

[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"
style = "green"

[directory]
disabled = false
truncation_length = 3
style = "green"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
