"$schema" = 'https://starship.rs/config-schema.json'

format = """
[$os]()  \
[$hostname](fg:red)\
[$username](fg:mauve)  \
[$directory](fg:blue)  \
[$git_branch$git_status](fg:orange)  \
[$python](fg:green)  \
$line_break$character"""

palette = 'tokyo_night'

[palettes.catppuccin_mocha]
red = "#f38ba8"
orange = "#fab387" # peach in cattppuccin specifically
green = "#a6e3a1"
blue = "#89b4fa"
mauve = "#cba6f7"

[palettes.tokyo_night]
red = "#f7768e"
orange = "#ff9e64"
green = "#9ece6a"
blue = "#7aa2f7"
mauve = "#bb9af7"

[hostname]
ssh_only = true
ssh_symbol = '󰑔 '
format = '$ssh_symbol$hostname  '

[os]
disabled = false
format = '$symbol'

[os.symbols]
Windows = "󰍲"
Linux = "󰌽"
Arch = "󰣇"
Debian = "󰣚"
NixOS = ""
Macos = ""

[username]
show_always = true
format = ' $user'

[directory]
format = " $path"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚 "
"Pictures" = ""
"code" = "󰲋 "
"dotfiles" = " "

[git_branch]
symbol = ""
format = '$symbol $branch'

[git_status]
format = '$all_status$ahead_behind'

[python]
symbol = ""
format = '$symbol $version $virtualenv'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:green)'
vimcmd_replace_symbol = '[](bold fg:green)'
vimcmd_visual_symbol = '[](bold fg:green)'
