#!/bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct

exec xconfigure &
exec sxhkd &
exec $HOME/.config/dunst/launch.sh &
exec xiccd &
exec playerctld daemon &
exec picom -b &

if [ "$#" -eq 0 ]; then
    exec i3
else
    exec "$@"
fi
