#!/bin/sh

setxkbmap -option shift:both_capslock
setxkbmap -option caps:escape
xrdb -merge "$HOME/.config/X11/.Xresources"
exec sxhkd &
exec picom -b &
exec $HOME/.config/dunst/launch.sh &
exec xiccd &
xsetroot -solid "#000000"

if [ "$#" -eq 0 ]; then
    exec i3
else
    exec "$@"
fi
